go_library(
    name = "stream",
    srcs = [
        "aggregator.go",
        "csv.go",
        "filter.go",
        "flatten.go",
        "go.go",
        "gob.go",
        "groupby.go",
        "itertools.go",
        "json.go",
        "sink.go",
        "source.go",
        "stream.go",
        "tsv.go",
        "value_bool.go",
        "value_empty.go",
        "value_float.go",
        "value_int.go",
        "value_stream.go",
        "value_string.go",
    ],
)
